version: '3.8'
services:
  app:
    build:
      context: ./
    environment:
      - ENV=${ENV}
      - REDIS_HOST=${REDIS_HOST}
      - TZ=${TZ}
      - BOT_SECRET_TOKEN=${BOT_SECRET_TOKEN}
      - GIPHY_API_KEY=${GIPHY_API_KEY}
      - BIBLE_API_KEY=${BIBLE_API_KEY}
    restart: unless-stopped
    links:
      - redis
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
volumes:
  redis_data:
