version: '3.8'
services:
  app:
    env_file:
      - .env
    build: 
      context: ./
    links:
      - redis
  redis:
    image: redis
    volumes:
      - redis_data:/redis_data
volumes:
  redis_data: