version: '3.8'
services:
  app:
    build:
      context: ./
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      REDIS_HOST: redis
    env_file:
      - .env
    links:
      - redis
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  redis_data:
