steps:
- uses: actions/ssh-auth@v1
  with:
    username: github
    hostname: 178.132.77.106
    port: 50000
    private-key: ${{ secrets.SSH_PRIVATE_KEY }}
- run: ssh github@<HOSTNAME> "echo 'Hello from the Raspberry Pi'"
